/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StationComparison } from "./StationComparison";
import { StationComparisonCountArgs } from "./StationComparisonCountArgs";
import { StationComparisonFindManyArgs } from "./StationComparisonFindManyArgs";
import { StationComparisonFindUniqueArgs } from "./StationComparisonFindUniqueArgs";
import { DeleteStationComparisonArgs } from "./DeleteStationComparisonArgs";
import { StationComparisonService } from "../stationComparison.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => StationComparison)
export class StationComparisonResolverBase {
  constructor(
    protected readonly service: StationComparisonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "StationComparison",
    action: "read",
    possession: "any",
  })
  async _stationComparisonsMeta(
    @graphql.Args() args: StationComparisonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [StationComparison])
  @nestAccessControl.UseRoles({
    resource: "StationComparison",
    action: "read",
    possession: "any",
  })
  async stationComparisons(
    @graphql.Args() args: StationComparisonFindManyArgs
  ): Promise<StationComparison[]> {
    return this.service.stationComparisons(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => StationComparison, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "StationComparison",
    action: "read",
    possession: "own",
  })
  async stationComparison(
    @graphql.Args() args: StationComparisonFindUniqueArgs
  ): Promise<StationComparison | null> {
    const result = await this.service.stationComparison(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StationComparison)
  @nestAccessControl.UseRoles({
    resource: "StationComparison",
    action: "delete",
    possession: "any",
  })
  async deleteStationComparison(
    @graphql.Args() args: DeleteStationComparisonArgs
  ): Promise<StationComparison | null> {
    try {
      return await this.service.deleteStationComparison(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
