/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Shift } from "./Shift";
import { ShiftCountArgs } from "./ShiftCountArgs";
import { ShiftFindManyArgs } from "./ShiftFindManyArgs";
import { ShiftFindUniqueArgs } from "./ShiftFindUniqueArgs";
import { DeleteShiftArgs } from "./DeleteShiftArgs";
import { ShiftService } from "../shift.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Shift)
export class ShiftResolverBase {
  constructor(
    protected readonly service: ShiftService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "read",
    possession: "any",
  })
  async _shiftsMeta(
    @graphql.Args() args: ShiftCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Shift])
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "read",
    possession: "any",
  })
  async shifts(@graphql.Args() args: ShiftFindManyArgs): Promise<Shift[]> {
    return this.service.shifts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Shift, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "read",
    possession: "own",
  })
  async shift(
    @graphql.Args() args: ShiftFindUniqueArgs
  ): Promise<Shift | null> {
    const result = await this.service.shift(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shift)
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "delete",
    possession: "any",
  })
  async deleteShift(
    @graphql.Args() args: DeleteShiftArgs
  ): Promise<Shift | null> {
    try {
      return await this.service.deleteShift(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
